# Welcome to Jekyll!

# Site Settings
title: "Haoyu Zhao"
description: "Research Fellow at NUS"
repository: "gulucaptain/gulucaptain.github.io"
url: "https://gulucaptain.github.io"
baseurl: ""
enable_google_scholar_stats: false
cloudflare_web_analytics:
  enabled: true
  token: "75c45d60f30a4389b57dafcc4b6c7986"
mapmyvisitors:
  enabled: true
  show_on_page: true
  title: "Visitor Map"
  tracking_note: "Live visitor tracking."
  widget_width: 300
  embed_src: "//mapmyvisitors.com/map.js?d=mBonwYjYWvh6zSi4II7xWcMdL4tYcCkChnezOI_I3xo&cl=ffffff&w=a"

# SEO Related (Optional - leave empty if not used)
google_site_verification:
bing_site_verification:
baidu_site_verification:

# Site Author
author:
  name: "Haoyu Zhao (浩宇)"
  avatar: "/images/zhaohaoyu.jpg"
  position: "Research Fellow"
  bio_label: "Motto:"
  bio: "Every little helps."
  employer: "National University of Singapore"
  location: "Singapore"
  googlescholar: "https://scholar.google.com/citations?user=pCGM7jwAAAAJ&hl=zh-CN"
  email: "zhaohaoyu@nus.edu.sg"
  github: "gulucaptain"
  linkedin:

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Asia/Singapore

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Whitelist
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Include _pages
include:
  - _pages

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

# Exclude list
exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - vendor
